#!/bin/sh
# postinst script for se3-clonage
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    install|configure)



	### on suppose que l'on est sous debian  ####
	WWWPATH="/var/www"
	## recuperation des variables necessaires pour interoger mysql ###
	if [ -e $WWWPATH/se3/includes/config.inc.php ]; then
		dbhost=`cat $WWWPATH/se3/includes/config.inc.php | grep "dbhost=" | cut -d = -f2 | cut -d \" -f2`
		dbname=`cat $WWWPATH/se3/includes/config.inc.php | grep "dbname=" | cut	-d = -f 2 |cut -d \" -f 2`
		dbuser=`cat $WWWPATH/se3/includes/config.inc.php | grep "dbuser=" | cut -d = -f 2 | cut -d \" -f 2`
		dbpass=`cat $WWWPATH/se3/includes/config.inc.php | grep "dbpass=" | cut -d = -f 2 | cut -d \" -f 2`
	else
		echo "Fichier de configuration inaccessible, le script ne peut se poursuivre."
		exit 1
	fi

	test_exist=`echo "SELECT value FROM params WHERE name='clonage'" | mysql -h $dbhost $dbname -u $dbuser -p$dbpass -N`
	if [ "X$test_exist" = "X" ]; then # if empty
		echo "INSERT INTO params VALUES ('', 'clonage', '0', 0, 'Activation du serveur de boot pxe - udpcast / unattented', 6)" | mysql -h $dbhost $dbname -u $dbuser -p$dbpass -N
	fi

	echo "CREATE TABLE IF NOT EXISTS se3_tftp_action (
id INT(11),
mac VARCHAR(255),
name VARCHAR(255),
date INT(11),
type VARCHAR(255),
num_op INT(11),
infos VARCHAR(255)
);" | mysql -h $dbhost $dbname -u $dbuser -p$dbpass -N

	echo "DROP TABLE IF EXISTS se3_tftp_sauvegardes;
CREATE TABLE IF NOT EXISTS se3_tftp_sauvegardes (
id INT( 11 ) NOT NULL ,
name VARCHAR( 255 ) NOT NULL ,
mac VARCHAR( 255 ) NOT NULL ,
partition VARCHAR( 255 ) NOT NULL ,
image VARCHAR( 255 ) NOT NULL ,
date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
descriptif TEXT NOT NULL,
df TEXT NOT NULL,
partitionnement TEXT NOT NULL,
identifiant int(11) NOT NULL auto_increment,
PRIMARY KEY  (identifiant)
);" | mysql -h $dbhost $dbname -u $dbuser -p$dbpass -N


	echo "DROP TABLE IF EXISTS se3_tftp_rapports;
CREATE TABLE IF NOT EXISTS se3_tftp_rapports (
id INT( 11 ) NOT NULL ,
name VARCHAR( 255 ) NOT NULL ,
mac VARCHAR( 255 ) NOT NULL ,
date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
tache VARCHAR( 255 ) NOT NULL ,
statut VARCHAR( 255 ) NOT NULL ,
descriptif TEXT NOT NULL,
identifiant int(11) NOT NULL auto_increment,
PRIMARY KEY  (identifiant)
);" | mysql -h $dbhost $dbname -u $dbuser -p$dbpass -N


# on rend executable les script sudo et sbin
[ -e /usr/share/se3/scripts/se3_tftp_boot_pxe.sh ] && chmod +x /usr/share/se3/scripts/se3_tftp_boot_pxe.sh
[ -e /usr/share/se3/scripts/recup_rapport.php ] && chmod +x /usr/share/se3/scripts/recup_rapport.php
[ -e /usr/share/se3/scripts/pxe_gen_cfg.sh ] && chmod +x /usr/share/se3/scripts/pxe_gen_cfg.sh
[ -e /usr/share/se3/scripts/se3_tftp_menage_atq.sh ] && chmod +x /usr/share/se3/scripts/se3_tftp_menage_atq.sh

[ -e /usr/share/se3/sbin/controle_actions_tftp.sh ] && chmod +x /usr/share/se3/sbin/controle_actions_tftp.sh

##### ADD good line in /etc/sudoers.conf if necessary and restart sudo
TEMOIN_CHGT_SUDO="n"
# TEST=$(grep "NOPASSWD:SE3CLONAGE" /etc/sudoers)
if [ ! "$(grep "NOPASSWD:SE3CLONAGE" /etc/sudoers)" ]; then
	# Insertion de l'autorisation de lancement par www-se3
	sed -i 's/^\(www-se3.*\)$/\1,NOPASSWD:SE3CLONAGE/' /etc/sudoers
	TEMOIN_CHGT_SUDO="y"
fi

# TEST=$(cat /etc/sudoers | grep "Cmnd_Alias SE3CLONAGE")

if [ ! "$(grep "Cmnd_Alias SE3CLONAGE" /etc/sudoers)" ]; then
	# On insère toute la ligne des commandes
	sed -i 's|^\(# Cmnd alias specification.*\)$|\1\nCmnd_Alias SE3CLONAGE=/usr/share/se3/scripts/se3_tftp_boot_pxe.sh,/usr/share/se3/scripts/pxe_gen_cfg.sh,/usr/share/se3/scripts/recup_rapport.php,/usr/share/se3/scripts/se3_tftp_menage_atq.sh|' /etc/sudoers
	TEMOIN_CHGT_SUDO="y"
else
	# La ligne Cmnd_Alias SE3CLONAGE existe déjà (avec au moins une commande donc)
# 	TEST1=$(cat /etc/sudoers | grep "/usr/share/se3/scripts/se3_tftp_boot_pxe.sh")
	if [ ! "$(grep "/usr/share/se3/scripts/se3_tftp_boot_pxe.sh" /etc/sudoers)" ]; then
		# On ajoute la commande au premier rang
		sed -i 's|Cmnd_Alias SE3CLONAGE=|Cmnd_Alias SE3CLONAGE=/usr/share/se3/scripts/se3_tftp_boot_pxe.sh,|' /etc/sudoers
		TEMOIN_CHGT_SUDO="y"
	fi

# 	TEST2=$(cat /etc/sudoers | grep "/usr/share/se3/scripts/pxe_gen_cfg.sh")
	if [ ! "$(grep "/usr/share/se3/scripts/pxe_gen_cfg.sh" /etc/sudoers)" ]; then
		# On ajoute la commande au premier rang
		sed -i 's|Cmnd_Alias SE3CLONAGE=|Cmnd_Alias SE3CLONAGE=/usr/share/se3/scripts/pxe_gen_cfg.sh,|' /etc/sudoers
		TEMOIN_CHGT_SUDO="y"
	fi

# 	TEST3=$(cat /etc/sudoers | grep "/usr/share/se3/scripts/recup_rapport.php")
	if [ ! "$(grep "/usr/share/se3/scripts/recup_rapport.php" /etc/sudoers)" ]; then
		# On ajoute la commande au premier rang
		sed -i 's|Cmnd_Alias SE3CLONAGE=|Cmnd_Alias SE3CLONAGE=/usr/share/se3/scripts/recup_rapport.php,|' /etc/sudoers
		TEMOIN_CHGT_SUDO="y"
	fi

# 	TEST4=$(cat /etc/sudoers | grep "/usr/share/se3/scripts/se3_tftp_menage_atq.sh")
	if [ ! "$(grep "/usr/share/se3/scripts/se3_tftp_menage_atq.sh" /etc/sudoers)" ]; then
		# On ajoute la commande au premier rang
		sed -i 's|Cmnd_Alias SE3CLONAGE=|Cmnd_Alias SE3CLONAGE=/usr/share/se3/scripts/se3_tftp_menage_atq.sh,|' /etc/sudoers
		TEMOIN_CHGT_SUDO="y"
	fi
fi

if [ "$TEMOIN_CHGT_SUDO" = "y" ]; then
	/etc/init.d/sudo restart
fi

mkdir -p /etc/se3/www-tools/tftp
chmod 770 /etc/se3/www-tools/tftp
chown www-se3:root /etc/se3/www-tools/tftp
if [ -e "/tftpboot/pxelinux.cfg" ]; then
  chown www-se3:root /tftpboot/pxelinux.cfg
fi

/usr/sbin/update-rc.d -f atftpd remove

# Activation par inetd.conf
[ "$test_exist" != "0" ] && /usr/share/se3/scripts/se3_tftp_boot_pxe.sh start


	;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.



exit 0


